name: xeus-cling
channels:
  - Quantstack
  - conda-forge
dependencies:
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - notebook
  - eigen
  - numpy
  - matplotlib
  - xplot=0.15.0
  - xeus-cling=0.8.1
  - bqplot=0.11.5
  - widgetsnbextension >=3.0.0
