ARG BASE_IMAGE=dustynv/ros:humble-pytorch-l4t-r32.7.1
FROM ${BASE_IMAGE} AS ros2cli.880.patch

WORKDIR /opt/ros/humble/install/lib/python3.6/site-packages/
RUN wget https://patch-diff.githubusercontent.com/raw/ros2/ros2cli/pull/880.patch -O - | patch -p2

FROM ros2cli.880.patch

RUN pip install Adafruit_MotorHAT
WORKDIR /root
