url: https://vikasdhiman.info
baseurl: /ECE417-F24-Mobile-Robots
remote_theme:  samarsault/plainwhite-jekyll
title: Mobile  Robots (ECE417-F24) at the University of Maine
author: Vikas Dhiman
description: Mobile  Robots (ECE417-F24) at the University of Maine
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Mobile Robots (ECE417)
  tagline: |
     Perception, Planning and Control for Mobile Robots

  sitemap: true

  search: true

  html_lang: "en"

  navigation:
    - title: Syllabus
      url: "https://docs.google.com/document/d/e/2PACX-1vQJuraDoCy1Sn7cm8hdzG_3uvrlI6fiZaCLCvXtGqJvyGe2lNgMkGSz8pZZwJKypAFKuZR2TonI5Pqu/pub"
    - title: Schedule
      url: "https://docs.google.com/spreadsheets/d/1k-nGcetapCx0A1oiH9MzKOYh6n_ZnszZq3CxtD5ovdQ/pubhtml?gid=976795384&single=true"
    - title: Zoom Link
      url: "https://maine.zoom.us/j/82357016182?pwd=weRkg7PnszrpwbsqXzBXXm9rMe5MwD.1"

  portfolio_image: images/jetbot.jpg
