url: https://vikasdhiman.info
baseurl: /ECE498-Mobile-Robots
remote_theme:  samarsault/plainwhite-jekyll
title: Mobile  Robots (ECE498) at the University of Maine
author: Vikas Dhiman
description: Mobile  Robots (ECE498) at the University of Maine
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


header_pages:
  - syllabus.md
  - labs.md


plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Mobile Robots (ECE498)
  tagline: |
     Perception, Planning and Control for Mobile Robots

  sitemap: true

  search: true

  html_lang: "en"

  navigation:
    - title: Schedule
      url: "https://docs.google.com/document/d/e/2PACX-1vQJuraDoCy1Sn7cm8hdzG_3uvrlI6fiZaCLCvXtGqJvyGe2lNgMkGSz8pZZwJKypAFKuZR2TonI5Pqu/pub"

  portfolio_image: images/jetbot.jpg
